version: "3"

services:
  web:
    build: .
    command: gunicorn jwt_django.wsgi:application --access-logfile - --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    ports:
      - "80:8000"

